# Generated by Django 4.2.30 on 2026-06-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('attack', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
                ('str_bonus', models.IntegerField(default=0)),
                ('agi_bonus', models.IntegerField(default=0)),
                ('vit_bonus', models.IntegerField(default=0)),
                ('int_bonus', models.IntegerField(default=0)),
                ('dex_bonus', models.IntegerField(default=0)),
                ('luk_bonus', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
