# Generated by Django 4.2.30 on 2026-06-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=50)),
                ('nivel', models.IntegerField(default=1)),
                ('transclasse', models.BooleanField(default=False)),
                ('forca', models.IntegerField(default=1)),
                ('agilidade', models.IntegerField(default=1)),
                ('vitalidade', models.IntegerField(default=1)),
                ('inteligencia', models.IntegerField(default=1)),
                ('destreza', models.IntegerField(default=1)),
                ('sorte', models.IntegerField(default=1)),
                ('equipamentos', models.JSONField(default=dict)),
            ],
        ),
    ]
